export default {
	AUTH_START: 'AUTH_START',
	AUTH_SUCCESS: 'AUTH_SUCCESS',
	AUTH_FAILED: 'AUTH_FAILED',
	REFRESH_TOKEN_START: 'REFRESH_TOKEN_START',
	REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
	REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED',
};
